apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        bucketNames:
          chunks: loki-logs
          ruler: loki-logs
          admin: loki-logs
        type: s3
        s3:
          endpoint: minio.storage:9000
          insecure: true
          bucketnames: loki-logs
          access_key_id: minioadmin  # Use secrets in production
          secret_access_key: minioadmin
          s3forcepathstyle: true
      auth_enabled: false
      compactor:
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
      limits_config:
        retention_period: 336h  # 14 days
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h  # 7 days
        max_global_streams_per_user: 10000
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20
      ruler:
        enabled: true
        storage:
          type: s3
          s3:
            endpoint: minio.storage:9000
            bucketnames: loki-logs
            access_key_id: minioadmin
            secret_access_key: minioadmin
            s3forcepathstyle: true
        ring:
          kvstore:
            store: inmemory
        enable_api: true
      distributor:
        ring:
          kvstore:
            store: inmemory
    persistence:
      enabled: false
    serviceMonitor:
      enabled: true
    gateway:
      enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    monitoring:
      dashboards:
        enabled: true
      rules:
        enabled: true
        alerting: true
      serviceMonitor:
        enabled: true
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
