apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus/helm-release.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/system-monitoring.json

commonLabels:
  app.kubernetes.io/component: monitoring
