apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crate-operator
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: crate-operator
      version: ">=2.0.0"
      sourceRef:
        kind: HelmRepository
        name: crate-operator
        namespace: flux-system
  install:
    createNamespace: true
  values:
    operator:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crate-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://crate.github.io/crate-operator