apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "45.7.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      enabled: false  # We'll deploy Grafana separately
    prometheus:
      prometheusSpec:
        retention: 30d
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
