apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - grafana/helm-release.yaml
  - tempo/helm-release.yaml
  - loki/helm-release.yaml
  - loki/rules.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/application-insights.json

commonLabels:
  app.kubernetes.io/component: observability
